
//======================== USUARIOS ========================

###
GET http://localhost:3000/users/
x-auth: admin

###
POST http://localhost:3000/users/
content-type: application/json
x-auth: admin

{
    "name": "XDDDDDDDDDDDDDD",
    "mail": "vamo@xd.com",
    "phone": "9832839120",
    "image": "photophoto",
    "pass": "fghwsfhdbfh12"
}

###
PUT http://localhost:3000/users/
content-type: application/json
x-auth: admin

{
    "id": "",
    "name": "pruebaUsuario123",
    "mail": "prueba123@gmail.com",
    "phone": "0987654321",
    "image": "fotoUsuario123",
    "pass": "0987"
}

###
DELETE http://localhost:3000/users/
x-auth: admin

//======================== PRODUCTOS ========================

###
GET http://localhost:3000/products/
x-auth: admin


###
POST http://localhost:3000/products/
content-type: application/json
x-auth: admin

{
    "name": "pruebaProducto",
    "description": "Esto es una prueba",
    "price": "5",
    "stock": "20",
    "image": "fotoProducto"
}

###
PUT http://localhost:3000/products/
content-type: application/json
x-auth: admin

{
    "name": "producto chido",
    "description": "una descripcion de un producto",
    "price": "3",
    "stock": "100",
    "image": "fotoProducto123"
}

###
DELETE http://localhost:3000/products/
x-auth: admin
